name: Convert from Markdown

on: push

permissions: read-all|write-all

jobs:
  convert-to-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: "src/markdown-guide.md -o markdown-guide.html"
          
